# Generated by Django 4.2.2 on 2023-06-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
