# Generated by Django 4.2.2 on 2023-06-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_alter_translation_translated_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
